
import React from 'react';
import { Topic, Question, QuestionType, Difficulty } from './types';

export const TOPICS: Topic[] = [
  { id: 'javascript', name: 'JavaScript', icon: '⚡', description: 'Cơ bản đến nâng cao về JS Engine, ES6+, Async...' },
  { id: 'typescript', name: 'TypeScript', icon: '📘', description: 'Type system, Generics, Decorators và Best practices.' },
  { id: 'react', name: 'React', icon: '⚛️', description: 'Hooks, Fiber, Context API và Performance Optimization.' },
  { id: 'html-css', name: 'HTML/CSS', icon: '🎨', description: 'Layout engine, CSS Grid, Flexbox và Accessibility.' },
  { id: 'backend', name: 'Backend & API', icon: '📁', description: 'Node.js, Databases, RESTful và Auth.' },
  { id: 'system-design', name: 'System Design', icon: '🏗️', description: 'Scalability, Load Balancing, Caching và Microservices.' }
];

export const MOCK_QUESTIONS: Question[] = [
  // JAVASCRIPT (10 questions)
  {
    id: 'js-1',
    topic: 'javascript',
    difficulty: Difficulty.MEDIUM,
    type: QuestionType.SINGLE,
    questionText: 'Kết quả của đoạn mã sau là gì?',
    codeSnippet: 'console.log(typeof NaN);',
    options: ['number', 'NaN', 'undefined', 'object'],
    correctAnswer: 'number',
    explanation: 'Trong JavaScript, NaN (Not-a-Number) có kiểu dữ liệu kỹ thuật là "number". Đây là một phần của tiêu chuẩn số thực IEEE 754.',
    reference: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN'
  },
  {
    id: 'js-2',
    topic: 'javascript',
    difficulty: Difficulty.HARD,
    type: QuestionType.MULTIPLE,
    questionText: 'Những thành phần nào thuộc về Web APIs (không phải của JS Engine)?',
    options: ['setTimeout', 'DOM', 'fetch', 'Call Stack'],
    correctAnswer: ['setTimeout', 'DOM', 'fetch'],
    explanation: 'setTimeout, DOM và fetch là các API do trình duyệt cung cấp (Web APIs). Call Stack là một phần của JavaScript Engine (như V8).',
  },
  {
    id: 'js-3',
    topic: 'javascript',
    difficulty: Difficulty.MEDIUM,
    type: QuestionType.FILL,
    questionText: 'Điền tên phương thức mảng dùng để tạo ra một mảng mới từ mảng cũ bằng cách áp dụng một hàm lên từng phần tử.',
    correctAnswer: 'map',
    explanation: 'Phương thức map() tạo ra một mảng mới với các kết quả của việc gọi một hàm được cung cấp cho mọi phần tử trong mảng gọi nó.',
  },
  {
    id: 'js-4',
    topic: 'javascript',
    difficulty: Difficulty.HARD,
    type: QuestionType.DRAG_DROP,
    questionText: 'Ghép nối các thuật ngữ sau với định nghĩa đúng của chúng.',
    matchingPairs: [
      { id: 'm1', left: 'Closure', right: 'Hàm ghi nhớ môi trường nơi nó được tạo ra' },
      { id: 'm2', left: 'Hoisting', right: 'Di chuyển khai báo lên đầu scope' },
      { id: 'm3', left: 'Event Delegation', right: 'Gán event listener cho element cha' }
    ],
    correctAnswer: { 'Closure': 'Hàm ghi nhớ môi trường nơi nó được tạo ra', 'Hoisting': 'Di chuyển khai báo lên đầu scope', 'Event Delegation': 'Gán event listener cho element cha' },
    explanation: 'Closure cho phép truy cập scope bên ngoài từ một hàm bên trong. Hoisting là hành vi mặc định của JS. Event Delegation tận dụng Event Bubbling.',
  },
  {
    id: 'js-5',
    topic: 'javascript',
    difficulty: Difficulty.MEDIUM,
    type: QuestionType.SINGLE,
    questionText: 'Giá trị của `this` trong một arrow function được xác định như thế nào?',
    options: [
      'Được xác định bởi cách hàm được gọi',
      'Được kế thừa từ lexical scope (scope cha)',
      'Luôn là đối tượng global',
      'Luôn là undefined trong strict mode'
    ],
    correctAnswer: 'Được kế thừa từ lexical scope (scope cha)',
    explanation: 'Arrow functions không có `this` riêng. Chúng kế thừa `this` từ scope bao quanh tại thời điểm chúng được định nghĩa.',
  },
  {
    id: 'js-6',
    topic: 'javascript',
    difficulty: Difficulty.MEDIUM,
    type: QuestionType.SINGLE,
    questionText: 'Kết quả của phép so sánh: `0 == "0"` và `0 === "0"` lần lượt là?',
    options: ['true, true', 'false, false', 'true, false', 'false, true'],
    correctAnswer: 'true, false',
    explanation: 'Toán tử `==` thực hiện ép kiểu (type coercion) nên 0 bằng "0". Toán tử `===` so sánh cả giá trị và kiểu dữ liệu.',
  },
  {
    id: 'js-7',
    topic: 'javascript',
    difficulty: Difficulty.HARD,
    type: QuestionType.SINGLE,
    questionText: 'Đoạn mã sau in ra gì?',
    codeSnippet: 'for (var i = 0; i < 3; i++) {\n  setTimeout(() => console.log(i), 1);\n}',
    options: ['0, 1, 2', '3, 3, 3', 'undefined, undefined, undefined', 'Lỗi ReferenceError'],
    correctAnswer: '3, 3, 3',
    explanation: 'Do sử dụng `var`, biến `i` được hoisting và dùng chung một scope cho toàn bộ vòng lặp. Khi setTimeout chạy, giá trị cuối của `i` là 3.',
  },
  {
    id: 'js-8',
    topic: 'javascript',
    difficulty: Difficulty.EASY,
    type: QuestionType.MULTIPLE,
    questionText: 'Những cách nào sau đây có thể dùng để khai báo biến trong ES6+?',
    options: ['var', 'let', 'const', 'define'],
    correctAnswer: ['var', 'let', 'const'],
    explanation: 'ES6 giới thiệu let và const. var vẫn được hỗ trợ từ các phiên bản trước.',
  },
  {
    id: 'js-9',
    topic: 'javascript',
    difficulty: Difficulty.MEDIUM,
    type: QuestionType.FILL,
    questionText: 'Từ khóa nào được sử dụng để bắt lỗi trong khối try...catch?',
    correctAnswer: 'catch',
    explanation: 'Khối catch nhận đối tượng lỗi được ném ra từ khối try.',
  },
  {
    id: 'js-10',
    topic: 'javascript',
    difficulty: Difficulty.MEDIUM,
    type: QuestionType.SINGLE,
    questionText: 'Phương thức nào biến một JSON string thành một JavaScript object?',
    options: ['JSON.stringify()', 'JSON.parse()', 'JSON.toObject()', 'JSON.convert()'],
    correctAnswer: 'JSON.parse()',
    explanation: 'JSON.parse() giải mã chuỗi JSON thành object, ngược lại với JSON.stringify().',
  },

  // TYPESCRIPT (10 questions)
  {
    id: 'ts-1',
    topic: 'typescript',
    difficulty: Difficulty.EASY,
    type: QuestionType.SINGLE,
    questionText: 'Từ khóa nào dùng để định nghĩa một kiểu dữ liệu mới có thể được mở rộng bằng cách khai báo lại?',
    options: ['type', 'interface', 'class', 'enum'],
    correctAnswer: 'interface',
    explanation: 'Interface trong TS có tính chất "declaration merging", cho phép định nghĩa lại để mở rộng, trong khi type alias thì không.',
  },
  {
    id: 'ts-2',
    topic: 'typescript',
    difficulty: Difficulty.MEDIUM,
    type: QuestionType.SINGLE,
    questionText: 'Sự khác biệt giữa `unknown` và `any` là gì?',
    options: [
      'Không có sự khác biệt',
      'unknown an toàn hơn any vì nó bắt buộc phải kiểm tra kiểu trước khi sử dụng',
      'any an toàn hơn unknown',
      'unknown chỉ dùng cho primitive types'
    ],
    correctAnswer: 'unknown an toàn hơn any vì nó bắt buộc phải kiểm tra kiểu trước khi sử dụng',
    explanation: 'Với unknown, bạn không thể gọi phương thức hoặc truy cập thuộc tính mà không thực hiện Type Narrowing.',
  },
  {
    id: 'ts-3',
    topic: 'typescript',
    difficulty: Difficulty.HARD,
    type: QuestionType.SINGLE,
    questionText: 'Utility type nào biến tất cả các thuộc tính của một interface thành readonly?',
    options: ['Readonly<T>', 'Partial<T>', 'Pick<T>', 'Final<T>'],
    correctAnswer: 'Readonly<T>',
    explanation: 'Readonly<T> tạo ra một kiểu mà tất cả các thuộc tính của T đều không thể gán lại giá trị.',
  },
  {
    id: 'ts-4',
    topic: 'typescript',
    difficulty: Difficulty.MEDIUM,
    type: QuestionType.FILL,
    questionText: 'Điền tên của tính năng cho phép truyền một kiểu dữ liệu như một tham số (thường dùng ký hiệu <T>).',
    correctAnswer: 'Generics',
    explanation: 'Generics cho phép tạo ra các thành phần (function, class, interface) có thể hoạt động với nhiều kiểu dữ liệu khác nhau mà vẫn giữ được tính an toàn kiểu.',
  },
  {
    id: 'ts-5',
    topic: 'typescript',
    difficulty: Difficulty.MEDIUM,
    type: QuestionType.MULTIPLE,
    questionText: 'Những toán tử nào sau đây liên quan đến Type Narrowing?',
    options: ['typeof', 'instanceof', 'in', 'as'],
    correctAnswer: ['typeof', 'instanceof', 'in'],
    explanation: 'typeof, instanceof và in dùng để kiểm tra kiểu thực tế của biến. "as" là Type Assertion, không phải Narrowing.',
  },
  {
    id: 'ts-6',
    topic: 'typescript',
    difficulty: Difficulty.HARD,
    type: QuestionType.SINGLE,
    questionText: 'Kết quả của `type T = string & number` là gì?',
    options: ['string | number', 'any', 'never', 'unknown'],
    correctAnswer: 'never',
    explanation: 'Intersection (&) của hai kiểu primitive không tương thích sẽ tạo ra kiểu `never` vì không có giá trị nào vừa là string vừa là number.',
  },
  {
    id: 'ts-7',
    topic: 'typescript',
    difficulty: Difficulty.MEDIUM,
    type: QuestionType.DRAG_DROP,
    questionText: 'Ghép nối Utility Type với chức năng tương ứng.',
    matchingPairs: [
      { id: 'u1', left: 'Partial', right: 'Biến mọi thuộc tính thành optional' },
      { id: 'u2', left: 'Required', right: 'Biến mọi thuộc tính thành bắt buộc' },
      { id: 'u3', left: 'Record', right: 'Tạo một object với key và value xác định' }
    ],
    correctAnswer: { 'Partial': 'Biến mọi thuộc tính thành optional', 'Required': 'Biến mọi thuộc tính thành bắt buộc', 'Record': 'Tạo một object với key và value xác định' },
    explanation: 'Đây là các Utility Types phổ biến dùng để biến đổi các interface có sẵn.',
  },
  {
    id: 'ts-8',
    topic: 'typescript',
    difficulty: Difficulty.EASY,
    type: QuestionType.SINGLE,
    questionText: 'File cấu hình chính của TypeScript project là gì?',
    options: ['package.json', 'ts-config.js', 'tsconfig.json', 'typescript.json'],
    correctAnswer: 'tsconfig.json',
    explanation: 'tsconfig.json chỉ định các file gốc và các tùy chọn trình biên dịch cần thiết cho dự án.',
  },
  {
    id: 'ts-9',
    topic: 'typescript',
    difficulty: Difficulty.HARD,
    type: QuestionType.SINGLE,
    questionText: 'Tính năng nào cho phép gọi phương thức mà không sợ lỗi nếu object bị null/undefined?',
    options: ['Nullish Coalescing', 'Optional Chaining', 'Type Assertion', 'Guarded Execution'],
    correctAnswer: 'Optional Chaining',
    explanation: 'Toán tử `?.` (Optional Chaining) dừng thực thi và trả về undefined nếu giá trị trước nó là nullish.',
  },
  {
    id: 'ts-10',
    topic: 'typescript',
    difficulty: Difficulty.MEDIUM,
    type: QuestionType.FILL,
    questionText: 'Từ khóa nào dùng để lấy kiểu của một biến hoặc thuộc tính trong TypeScript?',
    correctAnswer: 'typeof',
    explanation: 'Trong TypeScript, typeof dùng trong type context để trích xuất kiểu từ một giá trị thực tế.',
  },

  // REACT (10 questions)
  {
    id: 'react-1',
    topic: 'react',
    difficulty: Difficulty.MEDIUM,
    type: QuestionType.SINGLE,
    questionText: 'Hook nào được sử dụng để tối ưu hóa hiệu năng bằng cách ghi nhớ giá trị tính toán?',
    options: ['useEffect', 'useCallback', 'useMemo', 'useRef'],
    correctAnswer: 'useMemo',
    explanation: 'useMemo trả về một giá trị đã được memoized (ghi nhớ), giúp tránh tính toán lại không cần thiết ở mỗi lần render.',
  },
  {
    id: 'react-2',
    topic: 'react',
    difficulty: Difficulty.EASY,
    type: QuestionType.SINGLE,
    questionText: 'Trong React, thuộc tính nào dùng để định danh duy nhất các phần tử trong một danh sách?',
    options: ['id', 'key', 'index', 'ref'],
    correctAnswer: 'key',
    explanation: 'Key giúp React xác định phần tử nào thay đổi, thêm vào hoặc bị xóa bỏ để tối ưu quá trình Reconciliation.',
  },
  {
    id: 'react-3',
    topic: 'react',
    difficulty: Difficulty.HARD,
    type: QuestionType.MULTIPLE,
    questionText: 'Những hành động nào sau đây sẽ kích hoạt một component render lại?',
    options: ['Thay đổi state', 'Thay đổi props', 'Thay đổi một biến global', 'Component cha render lại'],
    correctAnswer: ['Thay đổi state', 'Thay đổi props', 'Component cha render lại'],
    explanation: 'React chỉ theo dõi state và props. Thay đổi biến global không làm component render lại trừ khi nó được đưa vào state.',
  },
  {
    id: 'react-4',
    topic: 'react',
    difficulty: Difficulty.MEDIUM,
    type: QuestionType.FILL,
    questionText: 'Cơ chế mà React sử dụng để cập nhật DOM thật một cách hiệu quả nhất được gọi là Virtual ___?',
    correctAnswer: 'DOM',
    explanation: 'Virtual DOM là một bản đại diện nhẹ của Real DOM trong bộ nhớ, dùng để tính toán các thay đổi tối thiểu cần thiết.',
  },
  {
    id: 'react-5',
    topic: 'react',
    difficulty: Difficulty.HARD,
    type: QuestionType.SINGLE,
    questionText: 'Hành vi của `useEffect` khi dependency array là `[]` (mảng rỗng) là gì?',
    options: [
      'Chạy sau mỗi lần render',
      'Chạy một lần duy nhất sau khi component mount',
      'Không bao giờ chạy',
      'Chạy khi component unmount'
    ],
    correctAnswer: 'Chạy một lần duy nhất sau khi component mount',
    explanation: 'Mảng rỗng nghĩa là effect không phụ thuộc vào bất kỳ giá trị nào, nên nó chỉ thực thi sau lần render đầu tiên.',
  },
  {
    id: 'react-6',
    topic: 'react',
    difficulty: Difficulty.MEDIUM,
    type: QuestionType.DRAG_DROP,
    questionText: 'Ghép nối Hook với mục đích sử dụng.',
    matchingPairs: [
      { id: 'rh1', left: 'useContext', right: 'Truy cập dữ liệu từ Global Provider' },
      { id: 'rh2', left: 'useRef', right: 'Truy cập trực tiếp DOM node hoặc lưu giá trị bền vững' },
      { id: 'rh3', left: 'useReducer', right: 'Quản lý state phức tạp với logic dispatch' }
    ],
    correctAnswer: { 'useContext': 'Truy cập dữ liệu từ Global Provider', 'useRef': 'Truy cập trực tiếp DOM node hoặc lưu giá trị bền vững', 'useReducer': 'Quản lý state phức tạp với logic dispatch' },
    explanation: 'Mỗi hook có một trách nhiệm cụ thể trong vòng đời component.',
  },
  {
    id: 'react-7',
    topic: 'react',
    difficulty: Difficulty.MEDIUM,
    type: QuestionType.SINGLE,
    questionText: 'Làm thế nào để truyền dữ liệu từ Component con lên Component cha?',
    options: [
      'Sử dụng Redux',
      'Sử dụng callback function truyền qua props',
      'Sử dụng context API',
      'Không thể truyền ngược dữ liệu'
    ],
    correctAnswer: 'Sử dụng callback function truyền qua props',
    explanation: 'Cha truyền một hàm cho Con, Con gọi hàm đó kèm dữ liệu làm đối số.',
  },
  {
    id: 'react-8',
    topic: 'react',
    difficulty: Difficulty.HARD,
    type: QuestionType.SINGLE,
    questionText: 'Trong Concurrent React (v18+), Hook nào dùng để đánh dấu một cập nhật state là không ưu tiên?',
    options: ['useTransition', 'useDeferredValue', 'useLayoutEffect', 'useSyncExternalStore'],
    correctAnswer: 'useTransition',
    explanation: 'useTransition cho phép render các cập nhật nặng ở background mà không làm treo UI.',
  },
  {
    id: 'react-9',
    topic: 'react',
    difficulty: Difficulty.EASY,
    type: QuestionType.FILL,
    questionText: 'Cú pháp viết tắt `<> ... </>` trong React dùng để thay thế cho Component ___?',
    correctAnswer: 'Fragment',
    explanation: 'Fragments cho phép bọc danh sách các phần tử mà không thêm node dư thừa vào DOM.',
  },
  {
    id: 'react-10',
    topic: 'react',
    difficulty: Difficulty.MEDIUM,
    type: QuestionType.SINGLE,
    questionText: 'Sự khác biệt chính giữa `useMemo` và `useCallback` là gì?',
    options: [
      'Không có sự khác biệt',
      'useMemo ghi nhớ giá trị, useCallback ghi nhớ function instance',
      'useCallback chạy nhanh hơn useMemo',
      'useMemo chỉ dùng cho object'
    ],
    correctAnswer: 'useMemo ghi nhớ giá trị, useCallback ghi nhớ function instance',
    explanation: 'useCallback(fn, deps) tương đương với useMemo(() => fn, deps).',
  },

  // HTML/CSS (10 questions)
  {
    id: 'html-1',
    topic: 'html-css',
    difficulty: Difficulty.EASY,
    type: QuestionType.SINGLE,
    questionText: 'Thuộc tính CSS nào dùng để tạo khoảng cách giữa các phần tử bên trong một flex container?',
    options: ['margin', 'padding', 'gap', 'spacing'],
    correctAnswer: 'gap',
    explanation: 'Thuộc tính gap (trước đây là grid-gap) hiện đã được hỗ trợ cho Flexbox để tạo khoảng cách giữa các items.',
  },
  {
    id: 'html-2',
    topic: 'html-css',
    difficulty: Difficulty.MEDIUM,
    type: QuestionType.MULTIPLE,
    questionText: 'Những thuộc tính nào ảnh hưởng đến kích thước tổng thể của một box trong mô hình "box-sizing: border-box"?',
    options: ['width', 'padding', 'border', 'margin'],
    correctAnswer: ['width', 'margin'],
    explanation: 'Với border-box, padding và border nằm trong width. Chỉ margin là nằm ngoài width và ảnh hưởng không gian chiếm dụng bên ngoài.',
  },
  {
    id: 'html-3',
    topic: 'html-css',
    difficulty: Difficulty.HARD,
    type: QuestionType.SINGLE,
    questionText: 'Thứ tự ưu tiên (specificity) của CSS selector nào là cao nhất?',
    options: ['#id', '.class', 'tag', 'inline style attribute'],
    correctAnswer: 'inline style attribute',
    explanation: 'Inline style có specificity cao nhất (1,0,0,0), trừ khi có !important.',
  },
  {
    id: 'html-4',
    topic: 'html-css',
    difficulty: Difficulty.MEDIUM,
    type: QuestionType.FILL,
    questionText: 'Điền tên thuộc tính CSS dùng để thay đổi thứ tự hiển thị của phần tử trong Flexbox/Grid mà không thay đổi thứ tự HTML.',
    correctAnswer: 'order',
    explanation: 'Thuộc tính order nhận giá trị số nguyên, giá trị thấp hơn sẽ hiển thị trước.',
  },
  {
    id: 'html-5',
    topic: 'html-css',
    difficulty: Difficulty.MEDIUM,
    type: QuestionType.DRAG_DROP,
    questionText: 'Ghép nối đơn vị đo lường với định nghĩa đúng.',
    matchingPairs: [
      { id: 'u1', left: 'rem', right: 'Dựa trên font-size của root element (html)' },
      { id: 'u2', left: 'em', right: 'Dựa trên font-size của chính phần tử đó hoặc cha' },
      { id: 'u3', left: 'vh', right: '1% chiều cao của viewport' }
    ],
    correctAnswer: { 'rem': 'Dựa trên font-size của root element (html)', 'em': 'Dựa trên font-size của chính phần tử đó hoặc cha', 'vh': '1% chiều cao của viewport' },
    explanation: 'Sử dụng đơn vị tương đối giúp thiết kế responsive tốt hơn.',
  },
  {
    id: 'html-6',
    topic: 'html-css',
    difficulty: Difficulty.EASY,
    type: QuestionType.SINGLE,
    questionText: 'Thẻ HTML nào được khuyến khích dùng cho nội dung bài viết chính để tăng SEO?',
    options: ['<div>', '<article>', '<section>', '<span>'],
    correctAnswer: '<article>',
    explanation: '<article> là thẻ ngữ nghĩa (semantic) đại diện cho một nội dung độc lập, có thể tái sử dụng.',
  },
  {
    id: 'html-7',
    topic: 'html-css',
    difficulty: Difficulty.HARD,
    type: QuestionType.SINGLE,
    questionText: 'Trong CSS Grid, giá trị `1fr` có ý nghĩa gì?',
    options: [
      '100% chiều rộng container',
      '1 phần của không gian còn trống (fraction)',
      '100px cố định',
      'Tương đương với 1em'
    ],
    correctAnswer: '1 phần của không gian còn trống (fraction)',
    explanation: 'fr (fraction) phân chia không gian linh hoạt sau khi đã trừ đi các kích thước cố định.',
  },
  {
    id: 'html-8',
    topic: 'html-css',
    difficulty: Difficulty.MEDIUM,
    type: QuestionType.SINGLE,
    questionText: 'Thuộc tính `position: sticky` hoạt động khi nào?',
    options: [
      'Luôn cố định tại một chỗ',
      'Dựa vào scroll của cha gần nhất có scroll',
      'Luôn dựa vào body',
      'Chỉ hoạt động trong IE'
    ],
    correctAnswer: 'Dựa vào scroll của cha gần nhất có scroll',
    explanation: 'Sticky kết hợp giữa relative và fixed tùy thuộc vào vị trí cuộn của người dùng.',
  },
  {
    id: 'html-9',
    topic: 'html-css',
    difficulty: Difficulty.MEDIUM,
    type: QuestionType.FILL,
    questionText: 'Pseudo-class nào được dùng để chọn phần tử khi người dùng di chuột qua?',
    correctAnswer: ':hover',
    explanation: ':hover kích hoạt khi con trỏ chuột nằm trên phần tử.',
  },
  {
    id: 'html-10',
    topic: 'html-css',
    difficulty: Difficulty.HARD,
    type: QuestionType.MULTIPLE,
    questionText: 'Những thuộc tính nào sau đây thuộc về CSS Flexbox?',
    options: ['justify-content', 'align-items', 'grid-template', 'flex-grow'],
    correctAnswer: ['justify-content', 'align-items', 'flex-grow'],
    explanation: 'grid-template chỉ dành cho CSS Grid.',
  },

  // BACKEND & API (10 questions)
  {
    id: 'backend-1',
    topic: 'backend',
    difficulty: Difficulty.MEDIUM,
    type: QuestionType.SINGLE,
    questionText: 'Mã trạng thái HTTP nào đại diện cho lỗi "Unauthorized"?',
    options: ['400', '401', '403', '404'],
    correctAnswer: '401',
    explanation: '401 Unauthorized có nghĩa là yêu cầu thiếu thông tin xác thực hợp lệ.',
  },
  {
    id: 'backend-2',
    topic: 'backend',
    difficulty: Difficulty.MEDIUM,
    type: QuestionType.SINGLE,
    questionText: 'REST API Method nào nên được dùng để cập nhật một phần của bản ghi?',
    options: ['POST', 'PUT', 'PATCH', 'UPDATE'],
    correctAnswer: 'PATCH',
    explanation: 'PATCH dùng cho việc cập nhật một phần, trong khi PUT dùng để thay thế toàn bộ bản ghi.',
  },
  {
    id: 'backend-3',
    topic: 'backend',
    difficulty: Difficulty.HARD,
    type: QuestionType.MULTIPLE,
    questionText: 'Những cơ chế nào thường dùng để bảo mật API?',
    options: ['OAuth2', 'JWT', 'API Keys', 'FTP'],
    correctAnswer: ['OAuth2', 'JWT', 'API Keys'],
    explanation: 'FTP là giao thức truyền file, không phải cơ chế bảo mật API.',
  },
  {
    id: 'backend-4',
    topic: 'backend',
    difficulty: Difficulty.MEDIUM,
    type: QuestionType.FILL,
    questionText: 'Trong SQL, từ khóa nào dùng để sắp xếp kết quả trả về?',
    correctAnswer: 'ORDER BY',
    explanation: 'ORDER BY cho phép sắp xếp theo một hoặc nhiều cột tăng dần (ASC) hoặc giảm dần (DESC).',
  },
  {
    id: 'backend-5',
    topic: 'backend',
    difficulty: Difficulty.HARD,
    type: QuestionType.SINGLE,
    questionText: 'Middleware trong Node.js (Express) là gì?',
    options: [
      'Một cơ sở dữ liệu',
      'Hàm có quyền truy cập vào request và response objects',
      'Một frontend framework',
      'Một loại server phần cứng'
    ],
    correctAnswer: 'Hàm có quyền truy cập vào request và response objects',
    explanation: 'Middleware nằm giữa request gửi tới và route handler, dùng để xử lý logic chung như log, auth...',
  },
  {
    id: 'backend-6',
    topic: 'backend',
    difficulty: Difficulty.MEDIUM,
    type: QuestionType.DRAG_DROP,
    questionText: 'Ghép nối HTTP Method với ý nghĩa ngữ nghĩa.',
    matchingPairs: [
      { id: 'b1', left: 'GET', right: 'Truy vấn dữ liệu' },
      { id: 'b2', left: 'POST', right: 'Tạo mới bản ghi' },
      { id: 'b3', left: 'DELETE', right: 'Xóa bản ghi' }
    ],
    correctAnswer: { 'GET': 'Truy vấn dữ liệu', 'POST': 'Tạo mới bản ghi', 'DELETE': 'Xóa bản ghi' },
    explanation: 'Sử dụng đúng method là quy tắc quan trọng trong thiết kế RESTful API.',
  },
  {
    id: 'backend-7',
    topic: 'backend',
    difficulty: Difficulty.HARD,
    type: QuestionType.SINGLE,
    questionText: 'Chỉ mục (Index) trong Database giúp ích gì?',
    options: [
      'Tăng tốc độ ghi dữ liệu',
      'Tăng tốc độ truy vấn dữ liệu',
      'Tiết kiệm dung lượng đĩa',
      'Tự động sao lưu dữ liệu'
    ],
    correctAnswer: 'Tăng tốc độ truy vấn dữ liệu',
    explanation: 'Index tạo ra cấu trúc dữ liệu bổ sung để tìm kiếm nhanh hơn, nhưng làm chậm thao tác ghi (Insert/Update).',
  },
  {
    id: 'backend-8',
    topic: 'backend',
    difficulty: Difficulty.EASY,
    type: QuestionType.SINGLE,
    questionText: 'Định dạng dữ liệu phổ biến nhất hiện nay cho các Web API là?',
    options: ['XML', 'JSON', 'YAML', 'CSV'],
    correctAnswer: 'JSON',
    explanation: 'JSON nhẹ, dễ đọc và hỗ trợ tốt bởi hầu hết ngôn ngữ lập trình hiện đại.',
  },
  {
    id: 'backend-9',
    topic: 'backend',
    difficulty: Difficulty.HARD,
    type: QuestionType.FILL,
    questionText: 'Từ khóa nào trong SQL dùng để kết hợp dữ liệu từ hai bảng dựa trên một cột chung?',
    correctAnswer: 'JOIN',
    explanation: 'JOIN (Inner, Left, Right, Full) dùng để liên kết các hàng từ nhiều bảng.',
  },
  {
    id: 'backend-10',
    topic: 'backend',
    difficulty: Difficulty.MEDIUM,
    type: QuestionType.MULTIPLE,
    questionText: 'Những cơ sở dữ liệu nào thuộc loại NoSQL?',
    options: ['MySQL', 'MongoDB', 'PostgreSQL', 'Redis'],
    correctAnswer: ['MongoDB', 'Redis'],
    explanation: 'MySQL và PostgreSQL là RDBMS (SQL). MongoDB là Document-based, Redis là Key-Value (NoSQL).',
  },

  // SYSTEM DESIGN (10 questions)
  {
    id: 'sys-1',
    topic: 'system-design',
    difficulty: Difficulty.HARD,
    type: QuestionType.SINGLE,
    questionText: 'Trong CAP Theorem, chữ "A" đại diện cho điều gì?',
    options: ['Atomicity', 'Availability', 'Auth', 'Aggregation'],
    correctAnswer: 'Availability',
    explanation: 'CAP Theorem khẳng định một hệ thống phân tán chỉ có thể đảm bảo 2 trong 3 yếu tố: Consistency, Availability, và Partition Tolerance.',
  },
  {
    id: 'sys-2',
    topic: 'system-design',
    difficulty: Difficulty.MEDIUM,
    type: QuestionType.SINGLE,
    questionText: 'Load Balancer làm nhiệm vụ gì?',
    options: [
      'Lưu trữ file tĩnh',
      'Phân phối traffic đến nhiều server',
      'Nén ảnh tự động',
      'Mã hóa mật khẩu'
    ],
    correctAnswer: 'Phân phối traffic đến nhiều server',
    explanation: 'Load Balancer giúp tăng tính sẵn sàng và khả năng chịu tải của hệ thống.',
  },
  {
    id: 'sys-3',
    topic: 'system-design',
    difficulty: Difficulty.HARD,
    type: QuestionType.MULTIPLE,
    questionText: 'Những phương pháp nào giúp mở rộng hệ thống (Scalability)?',
    options: ['Vertical Scaling', 'Horizontal Scaling', 'Code Refactoring', 'Database Sharding'],
    correctAnswer: ['Vertical Scaling', 'Horizontal Scaling', 'Database Sharding'],
    explanation: 'Vertical (tăng tài nguyên 1 máy), Horizontal (thêm máy), Sharding (chia nhỏ DB). Refactoring cải thiện code nhưng không phải phương pháp mở rộng hạ tầng.',
  },
  {
    id: 'sys-4',
    topic: 'system-design',
    difficulty: Difficulty.MEDIUM,
    type: QuestionType.FILL,
    questionText: 'Điền tên thành phần dùng để lưu trữ dữ liệu tạm thời nhằm tăng tốc độ truy cập cho các yêu cầu lặp lại.',
    correctAnswer: 'Cache',
    explanation: 'Caching (như Redis/Memcached) giúp giảm tải cho database và giảm latency.',
  },
  {
    id: 'sys-5',
    topic: 'system-design',
    difficulty: Difficulty.HARD,
    type: QuestionType.SINGLE,
    questionText: 'CDN (Content Delivery Network) giải quyết vấn đề gì chủ yếu?',
    options: ['Bảo mật database', 'Giảm latency bằng cách đưa nội dung gần người dùng hơn', 'Xử lý logic backend', 'Tạo báo cáo analytics'],
    correctAnswer: 'Giảm latency bằng cách đưa nội dung gần người dùng hơn',
    explanation: 'CDN phân phối các node lưu trữ ở nhiều vị trí địa lý khác nhau trên thế giới.',
  },
  {
    id: 'sys-6',
    topic: 'system-design',
    difficulty: Difficulty.MEDIUM,
    type: QuestionType.DRAG_DROP,
    questionText: 'Ghép nối thuật ngữ với mô tả.',
    matchingPairs: [
      { id: 's1', left: 'Microservices', right: 'Chia hệ thống thành các dịch vụ nhỏ độc lập' },
      { id: 's2', left: 'Monolith', right: 'Toàn bộ ứng dụng nằm trong một codebase duy nhất' },
      { id: 's3', left: 'Message Queue', right: 'Xử lý bất đồng bộ giữa các dịch vụ' }
    ],
    correctAnswer: { 'Microservices': 'Chia hệ thống thành các dịch vụ nhỏ độc lập', 'Monolith': 'Toàn bộ ứng dụng nằm trong một codebase duy nhất', 'Message Queue': 'Xử lý bất đồng bộ giữa các dịch vụ' },
    explanation: 'Đây là các kiến trúc và công cụ phổ biến trong thiết kế hệ thống hiện đại.',
  },
  {
    id: 'sys-7',
    topic: 'system-design',
    difficulty: Difficulty.HARD,
    type: QuestionType.SINGLE,
    questionText: 'Thứ tự ưu tiên của một Write-Through Cache là gì?',
    options: [
      'Ghi vào DB rồi mới cập nhật Cache',
      'Ghi vào Cache và DB cùng lúc',
      'Chỉ ghi vào Cache, định kỳ ghi vào DB',
      'Không bao giờ ghi vào DB'
    ],
    correctAnswer: 'Ghi vào Cache và DB cùng lúc',
    explanation: 'Write-through đảm bảo dữ liệu trong cache luôn mới nhất nhưng độ trễ ghi cao hơn.',
  },
  {
    id: 'sys-8',
    topic: 'system-design',
    difficulty: Difficulty.HARD,
    type: QuestionType.MULTIPLE,
    questionText: 'Các thành phần nào giúp đảm bảo tính chịu lỗi (Fault Tolerance)?',
    options: ['Redundancy', 'Failover', 'Replication', 'CORS'],
    correctAnswer: ['Redundancy', 'Failover', 'Replication'],
    explanation: 'CORS là chính sách bảo mật trình duyệt, không liên quan đến khả năng chịu lỗi hệ thống.',
  },
  {
    id: 'sys-9',
    topic: 'system-design',
    difficulty: Difficulty.MEDIUM,
    type: QuestionType.FILL,
    questionText: 'Tên của giao thức được dùng rộng rãi nhất để giao tiếp giữa client và server trên web?',
    correctAnswer: 'HTTP',
    explanation: 'HyperText Transfer Protocol là nền tảng của mọi giao tiếp dữ liệu trên web.',
  },
  {
    id: 'sys-10',
    topic: 'system-design',
    difficulty: Difficulty.HARD,
    type: QuestionType.SINGLE,
    questionText: 'Khái niệm "Consistent Hashing" thường được dùng trong trường hợp nào?',
    options: [
      'Để mã hóa mật khẩu người dùng',
      'Để phân bổ dữ liệu đều trên các node trong hệ thống phân tán',
      'Để kiểm tra tính toàn vẹn của file',
      'Để sắp xếp mảng'
    ],
    correctAnswer: 'Để phân bổ dữ liệu đều trên các node trong hệ thống phân tán',
    explanation: 'Consistent Hashing giúp tối thiểu hóa việc di chuyển dữ liệu khi một node được thêm vào hoặc xóa bỏ khỏi cluster.',
  }
];
